basePath: /
consumes:
- application/json
info:
  description: Documentation for Zip API
  title: File service API
  version: 1.0.0
paths:
  /health-check:
    get:
      description: Register the health check handler
      operationId: health-check
      responses:
        "200":
          description: Checks to see if file service is up and running
        "404":
          description: Not found
      tags:
      - check
  /zip/{reference}:
    get:
      description: Download Zip file from zip request reference
      operationId: download
      parameters:
      - description: reference of the zip file request
        in: path
        name: reference
        required: true
      responses:
        "200":
          description: Zip file download
        "404":
          description: Zip file download
      tags:
      - zip
  /zip/request:
    post:
      description: Makes a request for a set of files to be downloaded from S3
      
produces:
- application/json
schemes:
- http
swagger: "2.0"
