version: 2.1

workflows:
  pr-build-and-test:
    jobs:
      - test_zipper_service:
          name: test_zipper_service
      - build_zipper_service:
          name: build_zipper_service
          requires: [test_zipper_service]

orbs:
  zipper_service:
    commands:
      install_aws_cli:
        steps:
          - run:
              name: Install AWS CLI
              command: sudo pip3 install awscli --upgrade
      ecr_login:
        steps:
          - run:
              name: Login to ECR
              command: |
                temp_role=$(aws sts assume-role --role-arn arn:aws:iam::311462405659:role/sirius-ci --role-session-name ci)
                export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
                export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
                export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
                eval $(aws ecr get-login --no-include-email --region=eu-west-1)
    executors:
      python:
        docker: [image: circleci/python]

jobs:
  test_zipper_service:
    docker:
      - image:
    steps:
      - checkout
      - run:
          name: go_mod
          command: go mod download
      - run:
          name: unit_tests
          command:
  build_zipper_service:
    