version: 2.1

workflows:
  pr-build-and-test:
    jobs:
      - test_zipper_service:
          name: test_zipper_service
      - build_zipper_service:
          name: build_zipper_service
          requires: [test_zipper_service]

orbs:
  zipper_service:
    commands:
      install_aws_cli:
        steps:
          - run:
              name: Install AWS CLI
              command: sudo pip3 install awscli --upgrade
      ecr_login:
        steps:
          - run:
              name: Login to ECR
              command: |
                temp_role=$(aws sts assume-role --role-arn arn:aws:iam::311462405659:role/sirius-ci --role-session-name ci)
                export AWS_ACCESS_KEY_ID=$(echo $temp_role | jq .Credentials.AccessKeyId | xargs)
                export AWS_SECRET_ACCESS_KEY=$(echo $temp_role | jq .Credentials.SecretAccessKey | xargs)
                export AWS_SESSION_TOKEN=$(echo $temp_role | jq .Credentials.SessionToken | xargs)
                eval $(aws ecr get-login --no-include-email --region=eu-west-1)
    executors:
      python:
        docker: [image: circleci/python]

jobs:
  test_zipper_service:
    docker:
      - image: circleci/golang
    environment:
      TEST_RESULTS: /tmp/test-results
      GOTESTSUM_FORMAT: short-verbose
    steps:
      - checkout
      - run:
          name: go_mod
          command: go mod download
      - run: mkdir -p $TEST_RESULTS
      - run:
          name: unit_tests
          command: gotestsum --junitfile unit-tests.xml
      - store_test_results:
          path: /tmp/test-results

  build_zipper_service:
    executor: zipper_service/python
    parameters:
      container_repo_url:
        type: string
        default: 311462405659.dkr.ecr.eu-west-1.amazonaws.com/zipper_service
    steps:
      - checkout
      - zipper_service/install_aws_cli
      - setup_remote_docker:
          version: 18.06.0-ce
          docker_layer_caching: false
      - run:
          name: Build
          command: |
            docker build --file Dockerfile --tag zipper_service:latest .
      - zipper_service/ecr_login
      - run:
          name: Push container
          command: |
            export SHORT_HASH=${CIRCLE_SHA1:0:7} >> $BASH_ENV
            docker tag zipper_service:latest << parameters.container_repo_url >>:latest
            docker tag zipper_service:latest << parameters.container_repo_url >>:$CIRCLE_BRANCH-$SHORT_HASH
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              # We want all of the tags pushed
              docker push << parameters.container_repo_url >>
            else
              docker push << parameters.container_repo_url >>:$CIRCLE_BRANCH-$SHORT_HASH
            fi
