name: Test & Build

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
 run:
  shell: bash

jobs:
  test:
    name: 'Test File Service'
    runs-on: ubuntu-latest
    env:
      TEST_RESULTS: /tmp/test-results
      GOTESTSUM_FORMAT: short-verbose
      DATA_DIR: /tmp/localstack/data
      AWS_ACCESS_KEY_ID: localstack
      AWS_SECRET_ACCESS_KEY: localstack
      DEFAULT_REGION: eu-west-1
      AWS_S3_ENDPOINT: http://localhost:4566
      AWS_DYNAMODB_ENDPOINT: http://localhost:4566
      SECRETS_MANAGER_ENDPOINT: http://localhost:4566
    services:
      localstack:
        image: localstack/localstack:0.12.2
        env:
          DEFAULT_REGION: eu-west-1
          SERVICES: s3,dynamodb,secretsmanager
        ports:
          - 4566:4566
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go
      - uses: actions/setup-python
      - uses: unfor19/install-aws-cli-action@v1
      - run: |
          python -m pip install awscli-local
      - name: Localstack Setup
        working-directory: ./scripts/localstack
        run: |
          chmod +x localstack_init.sh
          ./localstack_init.sh

      - name: Resolve GO Dependencies
        run: |
          go mod download
      - run: |
          mkdir -p ${{ env.TEST_RESULTS }}
      - name: Run Unit and Intergration Tests
        run: |
          gotestsum --junitfile unit-tests.xml
